version: '2'
services:
  varnish:
    # keopx/varnish available tags: latest, 5.1, 5.0, 4.0.
    image: keopx/varnish:4.0
    ports:
      - "80:80"
      - "6082:6082"
    volumes:
      - ./config/varnish/default.vcl:/etc/varnish/default.vcl
      ## mattiasgeniar file: https://github.com/mattiasgeniar/varnish-4.0-configuration-templates
      # - ./config/varnish/drupal-template.vcl:/etc/varnish/default.vcl
      ## Niteman file: https://github.com/NITEMAN/varnish-bites/blob/master/varnish4/drupal-base.vcl
      # - ./config/varnish/drupal-base.vcl:/etc/varnish/default.vcl
    # environment:
      # - VARNISH_PORT=80
      # - VARNISH_MEMORY=500M
      # Next values only works with default default.vcl file.
      # - VARNISH_BACKEND_IP=web
      # - VARNISH_BACKEND_PORT=80
    links:
      - web
  web:
    # keopx/apache-php available tags: latest, 7.2, 7.1, 7.0, 5.6.
    image: keopx/apache-php:5.6
    ports:
      # 8008 works without varnish.
      - "8008:80"
      # - "443:443"
    volumes:
      - ./data/www:/var/www # Data.
      - ./config/vhosts:/etc/apache2/sites-enabled
      ### See: https://github.com/keopx/docker-lamp for more information.
      ## php.ini for php 7.x and remove environment varibles.
      - ./config/php/5.6/php.ini:/etc/php/5.6/apache2/php.ini
      ## Opcache for php 7.0
      # - ./config/php/opcache-recommended.ini:/etc/php/7.0/apache2/conf.d/10-opcache.ini
      ## APC for php 7.0. Necessary to works APCu in PHP 7.0.
      # - ./config/php/apc.ini:/etc/php/7.0/apache2/conf.d/20-apc.ini
      ## APCU for php 7.0
      # - ./config/php/apcu.ini:/etc/php/7.0/apache2/conf.d/20-apcu.ini
      ## Xdebug for php 7.0
      # - ./config/php/xdebug.ini:/etc/php/7.0/apache2/conf.d/20-xdebug.ini
      ## Xhprof for php 7.0
      #- ./config/php/xhprof.ini:/etc/php/7.0/apache2/conf.d/20-xhprof.ini
      ## Drush aliases support. e.g.
      # - ~/.drush:/root/.drush
      ## SSH support. e.g.
      # - ~/.ssh:/root/.ssh
    # environment:
      ### WARNING: Use only if you not use custom php.ini.
      ## ssmtp mail sender.
      # - PHP_SENDMAIL_PATH="/usr/sbin/ssmtp -t"
      ## SMTP server configruation: "domain:port" | "mail" server domain is mailhog name.
      # - PHP_SENDMAIL_DOMAIN=mail:1025
    working_dir: /var/www
